### ISSUE TITLE
RKI data in repo does not match official number

### ISSUE THREAD

**Issue by JonasHeidelberg** [zushicat/covid-19-data-crawler#1]
Hi,

thanks for sharing your work! I have one question - when I compare master/data/03-04-2020/communities_germany_rki.csv with the data I downloaded for the same day from NPGEO RKI ( https://opendata.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0.csv ), I see a large mismatch. E.g., for reportDate 2020-04-02, the sum of cases_day is 917 in your file, while the NPGEO file shows 2161 new cases. Do you understand where the difference come from? Are you doing some filtering which I didn't notice?

Thanks!
Jonas

**Comment by zushicat** [comment]
Dear Jonas,
the RKI data differentiates between sex and age group, stored in separate rows. I dropped these data points and accumulated those separations into one row per day and location.
